name: frontend 
on:
  push:
    branches:
    - main
jobs:
   build_staging:
     runs:on: ubuntu_latest
     environment:
       name: staging
     steps: 
       - uses: actions/checkout@v2 
       - name: install node.js
       - uses: actions/setup-node@v1
         with:
           node-version: 10.x
           
   
